#!/usr/bin/env python
from fastapi import FastAPI, HTTPException
import logging
import yaml
import uvicorn
from lib.rpc.xchrpc import RemoteProcedureCall
from lib.datalayer.handle import Handler
from pydantic import BaseModel
from typing import Optional

app = FastAPI()

with open("config.yaml", "r") as file:
    config = yaml.safe_load(file)

logger = logging.getLogger("uvicorn")

try:
    wallet_rpc = RemoteProcedureCall(
        host=config["rpc_connector"]["host"],
        port=int(config["rpc_connector"]["service_ports"]["wallet"]),
        private_wallet_cert_path=config["rpc_connector"]["private_wallet_cert_path"],
        private_wallet_key_path=config["rpc_connector"]["private_wallet_key_path"],
        network_fee=config["rpc_connector"]["default_network_fee"]
    )

    datalayer_rpc = RemoteProcedureCall(
        host=config["rpc_connector"]["host"],
        port=int(config["rpc_connector"]["service_ports"]["datalayer"]),
        private_wallet_cert_path=config["rpc_connector"]["private_wallet_cert_path"],
        private_wallet_key_path=config["rpc_connector"]["private_wallet_key_path"],
        network_fee=config["rpc_connector"]["default_network_fee"]
    )

    datahandler = Handler(datalayer_rpc)
except Exception as e:
    logger.error(f"Failed to initialize RPC connections: {e}")
    raise

class UpdateKeyRequest(BaseModel):
    store_id: str
    key: str
    value: str
    codec: str
    cose_ph: Optional[str] = None
    cose_uh: Optional[str] = None

@app.get("/check")
def check_status():
    try:
        result1 = wallet_rpc.check_available_wallets()
        result2 = wallet_rpc.check_wallets_synced()
        result3 = wallet_rpc.check_wallet_balance(wallet_id=config["rpc_connector"]["service_wallets"]["chia"])
        result4 = datalayer_rpc.datalayer_get_owned_stores()

        results = [result1, result2, result3, result4]

        # Verificar si alguno de los resultados contiene un error
        if any("error" in str(res) for res in results):
            error_messages = [res.get("error", "Unknown error") if isinstance(res, dict) else str(res) for res in results]
            raise ValueError(f"One or more checks returned an error: {error_messages}")

    except ValueError as ve:
        logger.error(f"ValueError during check: {ve}")
        raise HTTPException(status_code=400, detail=str(ve))
    except Exception as e:
        logger.error(f"Unexpected error during check: {e}")
        raise HTTPException(status_code=500, detail=str(e))

    logger.info("OK - all the checks are completed successfully")
    return {"status": "OK - all the checks are completed successfully!"}

@app.post("/datastore/key/update")
def update_key(request: UpdateKeyRequest):
    print(request)
    try:
        if request.codec == "cose":
            return datahandler.cose_push_data(request.store_id, request.key, request.value, request.cose_ph, request.cose_uh)
        elif request.codec == "hex":
            return datahandler.hex_push_data(request.store_id, request.key, request.value)
        else:
            raise HTTPException(status_code=400, detail="Invalid codec")
    except Exception as e:
        logger.error(f"Error updating key: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/datastore/key/read")
def read_key(store_id: str, key: str, codec: str):
    try:
        if codec == "cose":
            return datahandler.cose_read_data(store_id, key)
        elif codec == "hex":
            return datahandler.hex_read_data(store_id, key)
        else:
            raise HTTPException(status_code=400, detail="Invalid codec")
    except Exception as e:
        logger.error(f"Error reading key: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/datastore/key/list")
def list_keys(store_id: str):
    try:
        return datahandler.datastore_list_keys(store_id)
    except Exception as e:
        logger.error(f"Error listing keys: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.delete("/datastore/key/delete")
def delete_key(store_id: str, key: str):
    try:
        return datahandler.datastore_delete_key(store_id, key)
    except Exception as e:
        logger.error(f"Error deleting key: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/datastore/list")
def get_datastore_info():
    try:
        return datalayer_rpc.datalayer_get_owned_stores()
    except Exception as e:
        logger.error(f"Error retrieving datastore info: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/datastore/create")
def get_datastore_info():
    try:
        return datalayer_rpc.create_data_store()
    except Exception as e:
        logger.error(f"Error retrieving datastore info: {e}")
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000, log_level=config["log_level"])
